version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 500m
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  spring:
    image: dh5252/spring-prod
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m
    restart: always
    ports:
      - "8082:8080"
  nginx:
    image: dh5252/nginx-prod
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ~/nginx_data/conf:/etc/nginx/conf.d
      - ~/nginx_data/certs:/etc/nginx/certs
      

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dh5277/db_data
