name: CI/CD_back

on:
  push:
    branches:
      - chiwon
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI-CD :
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: chiwon

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ./Backend/.gradle/caches
            ./Backend/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('./Backend/**/*.gradle*', './Backend/**gradle-wrapper.properties')}}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make application.properites
        run: |
          mkdir ./Backend/src/main/resources
          cd ./Backend/src/main/resources
          echo "${{ secrets.PROPERTIES }}" > application.properties
        shell: bash
      
      - name: Build with Gradle
        run: |
          cd Backend
          ./gradlew build -x test
      - name: Docker build & push to prod
        run: |
          cd Backend
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-prod
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }}
          username: dh5277
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            cd capstone
            git checkout main
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-prod
            sudo docker-compose restart spring
            sudo docker image prune -f
